# Generated by Django 5.2.10 on 2026-01-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeupclass',
            name='remedial_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
