# Generated by Django 5.2.10 on 2026-01-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
